### PR TITLE
chore: remove unnecessary import

### PR DESCRIPTION
**Pull request by laglangyue**
remove some unnecessary import
we not supprot scala 2.12, so we don't need import Seq

### CODE REVIEW

**Review by lomigmegard — CHANGES_REQUESTED** [review]
Thanks for the MR! Please rebase on top of master. 

The imports formatting should be handled by scalafmt, your changes aren't required.

But indeed some imports aren't used 👍

**Comment by laglangyue** [comment]
I have been rebeased and exec `sbt clean compile` with java17 locally

**Comment by lomigmegard** [comment]
@laglangyue thanks, please run `sbt scalafmtAll` to format according to this repo's rules.

**Comment by laglangyue** [comment]
> @laglangyue thanks, please run `sbt scalafmtAll` to format according to this repo's rules.

done

**Review by lomigmegard — APPROVED** [review]
LGTM

**Pull request merged**
